/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppDictionary {
    'config': any;
    'items': any;
    'shown': boolean;
    'test': String;
    'userPhoto2': any;
  }
  interface AppDictionaryAttributes extends StencilHTMLAttributes {
    'config'?: any;
    'items'?: any;
    'shown'?: boolean;
    'test'?: String;
    'userPhoto2'?: any;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfileDupe {
    'name': string;
  }
  interface AppProfileDupeAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppProfile {
    'authUser': any;
    'name': string;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'authUser'?: any;
    'name'?: string;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AuthService {
    'changed': any;
    'config': any;
  }
  interface AuthServiceAttributes extends StencilHTMLAttributes {
    'changed'?: any;
    'config'?: any;
    'onAuthStateChanged'?: (event: CustomEvent) => void;
  }

  interface AppMain {
    'section': any;
  }
  interface AppMainAttributes extends StencilHTMLAttributes {
    'section'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppDictionary': Components.AppDictionary;
    'AppHome': Components.AppHome;
    'AppProfileDupe': Components.AppProfileDupe;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'AuthService': Components.AuthService;
    'AppMain': Components.AppMain;
  }

  interface StencilIntrinsicElements {
    'app-dictionary': Components.AppDictionaryAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile-dupe': Components.AppProfileDupeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'auth-service': Components.AuthServiceAttributes;
    'app-main': Components.AppMainAttributes;
  }


  interface HTMLAppDictionaryElement extends Components.AppDictionary, HTMLStencilElement {}
  var HTMLAppDictionaryElement: {
    prototype: HTMLAppDictionaryElement;
    new (): HTMLAppDictionaryElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileDupeElement extends Components.AppProfileDupe, HTMLStencilElement {}
  var HTMLAppProfileDupeElement: {
    prototype: HTMLAppProfileDupeElement;
    new (): HTMLAppProfileDupeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAuthServiceElement extends Components.AuthService, HTMLStencilElement {}
  var HTMLAuthServiceElement: {
    prototype: HTMLAuthServiceElement;
    new (): HTMLAuthServiceElement;
  };

  interface HTMLAppMainElement extends Components.AppMain, HTMLStencilElement {}
  var HTMLAppMainElement: {
    prototype: HTMLAppMainElement;
    new (): HTMLAppMainElement;
  };

  interface HTMLElementTagNameMap {
    'app-dictionary': HTMLAppDictionaryElement
    'app-home': HTMLAppHomeElement
    'app-profile-dupe': HTMLAppProfileDupeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'auth-service': HTMLAuthServiceElement
    'app-main': HTMLAppMainElement
  }

  interface ElementTagNameMap {
    'app-dictionary': HTMLAppDictionaryElement;
    'app-home': HTMLAppHomeElement;
    'app-profile-dupe': HTMLAppProfileDupeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'auth-service': HTMLAuthServiceElement;
    'app-main': HTMLAppMainElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
